version: '3.8'

services:
  mysqldb:
    image: mysql:8.1.0
    container_name: vl-hr-mysql-db
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vl-hr-dev-db

  vl-dev-adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    depends_on:
      - mysqldb

volumes:
  mysqldata:
